### PR TITLE
Add tests for ember#2.11.0-beta.4

### PR DESCRIPTION
**Pull request by andyhot**
- Showcases the "ReferenceError: mainContext is not defined" issue
- Includes the correct expected compiler outputs (the tests will still not pass until Ember fixes the usage of mainContext)

### CODE REVIEW

**Comment by andyhot** [comment]
Let me rebase this

**Comment by andyhot** [comment]
It's fine now - Travis should fail due to the mainContext issue now so perhaps you'd want to keep it in a branch until it passes?

**Comment by zoltan-nz** [comment]
Yep, I were just thinking about the same keeping in a branch or keeping it here, so we can rerun the test on jenkins, if the ember-template-compiler is fixed.

**Comment by zoltan-nz** [comment]
I'm not sure how can I merge in the main repo with keeping the branch on github, it looks like, I can do it with git in command line, but not on GitHub.

**Comment by zoltan-nz** [comment]
@andyhot I just created a new branch and merged your changes into that one. Thanks.

**Pull request merged**
