### PR TITLE
Allow compiling templates with ember#2.11.0

### PR DESCRIPTION
**Pull request by andyhot**
Ember#2.11.0 was released but didn't include https://github.com/emberjs/ember.js/commit/70a94bb2f9cac3e05a9bc4d3e3c039fa3a68bfa3
which resulted in #94 

I noticed however that ember-cli-htmlbars was able to compile templates in 2.11.0 so, using this patch grunt-ember-templates can now compile them too

### CODE REVIEW

**Comment by andyhot** [comment]
We should probably also release a #1.1.1 version with this and document the compatibility with ember#2.11.0

**Comment by zoltan-nz** [comment]
Thanks @andyhot. Could you please PR to my forked repo? The test changed but I havent merged it to this. What do you think?

**Comment by zoltan-nz** [comment]
this is the forked repo where test runner improved https://github.com/zoltan-nz/grunt-ember-templates

**Comment by andyhot** [comment]
Damn, I didn't notice you were referring to your own repo and was just searching for the code here. So, why isn't this here?

Just saw the code and tun the tests and it looks great. I'd say move it here (either in master or in branch) and I'll update this PR. Would really love to release the new version since ember#2.11 is out already

**Comment by andyhot** [comment]
I pushed all your changes in this PR, so it looks good to go. Do you think we could have a new release soon?

**Comment by zoltan-nz** [comment]
@andyhot Thanks, this is great. Appreciate it... I'm on the version bump and release the new one in a second.

**Comment by zoltan-nz** [comment]
@andyhot Sorry, I just realised, I created a branch in this repo, so the code was here in a branch, I forgot to mention... anyway, it was the same what you merged from my repository finally... I will remove those branches...

**Comment by zoltan-nz** [comment]
@andyhot v1.1.1 is released... Thanks for your help. You are fantastic.

**Pull request merged**
